### ISSUE TITLE
offset -1 is invalid

### ISSUE THREAD

**Issue by MXYLR** [seritools/sm_realbhop#2]
![image](https://user-images.githubusercontent.com/37480216/112711969-59426a80-8f07-11eb-82ed-bf518bca6f70.png)

**Comment by seritools** [comment]
Hey, this plugin is severely outdated and obsolete since 2016, when Valve officially added sv_enablebunnyhopping and the other related cvars to the game: https://blog.counter-strike.net/index.php/2016/10/16296/

I'd encourage you to use these cvars (bhop, stamina settings, air acceleration, etc) to get the desired effect.

**Comment by MXYLR** [comment]
hmmm so I think I need to mention it earlier... sry, I'm trying using this plugin in Black Mesa, and I see there is a server that uses this plugin, too. But when I try to use this plugin and it didn't work. I tried install the same version of sourcemod and it didn't work, too

**Comment by seritools** [comment]
@MXYLR Sorry, this was written a long time ago and exclusively for csgo back then. There are probably some behavioral changes between those games. You'll have to look into that yourself though as I'm long done with source modding ^^
